### ISSUE TITLE
Auto tag for CreateBucket Failed

### ISSUE THREAD

**Issue by HaijiangLi** [GorillaStack/auto-tag#127]
Hi everyone,
Auto tag  on the AWS Volumes is successfully, but create the s3 bucket failed.
I find some error in cloud watch, following below error messages:
{
    "errorType": "NoSuchTagSet",
    "errorMessage": "The TagSet does not exist",
    "name": "NoSuchTagSet",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 404,
        "extendedRequestId": "tQThinxLbxXV9bphcXP7ipPhj4j9v/Q81C9JL8GYvk9iaaZspPX8CmHMYYDbQeYOlhaGgPzYeo8=",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "Code": "NoSuchTagSet",
    "BucketName": "rzh-test-20240301",
    "RequestId": "T33RGEPRS3MPHYAS",
    "HostId": "tQThinxLbxXV9bphcXP7ipPhj4j9v/Q81C9JL8GYvk9iaaZspPX8CmHMYYDbQeYOlhaGgPzYeo8=",
    "message": "The TagSet does not exist",
    "stack": [
        "NoSuchTagSet: The TagSet does not exist",
        "    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)",
        "    at deserializeAws_restXmlGetBucketTaggingCommandError (/var/runtime/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4180:43)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20",
        "    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)",
        "    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22"
    ]
}

**Comment by HaijiangLi** [comment]
Does anyone have any ideas or solutions to this issue?

**Comment by angsm** [comment]
This happens on my lambda function as well.
