### ISSUE TITLE
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by matze1508** [GorillaStack/auto-tag#39]
Hey, 
while using your Skript this happens to the Cloudwatch log for autotag.The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

How can I change the authentification for eu-central-1 
Like: var s3 = new AWS.S3({signatureVersion: 'v4'});

**Comment by matze1508** [comment]
Edit
`START RequestId: a1ff8f86-ac3e-11e8-a87c-b92e03164e92 Version: $LATEST 

10:22:47
2018-08-30T10:22:47.349Z a1ff8f86-ac3e-11e8-a87c-b92e03164e92 { [InvalidTag: System Tags cannot be removed by requester] message: 'System Tags cannot be removed by requester', code: 'InvalidTag', region: null, time: Thu Aug 30 2018 10:22:47 GMT+0000 (UTC), requestId: '885E736F4E5001A4', extendedRequestId: '4LJU9m6PNylt2CyqL4tqMoMgIeZFF+bovox0a3vjCD4YzT+FK996e+7my6hXbKuvRfUiUDb5PHM=',

10:22:47
2018-08-30T10:22:47.989Z a1ff8f86-ac3e-11e8-a87c-b92e03164e92 InvalidTag: System Tags cannot be removed by requester at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/s3.js:350:35) at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Reques

10:22:48
2018-08-30T10:22:48.009Z a1ff8f86-ac3e-11e8-a87c-b92e03164e92 {"errorMessage":"System Tags cannot be removed by requester","errorType":"InvalidTag","stackTrace":["Request.extractError (/var/task/node_modules/aws-sdk/lib/services/s3.js:350:35)","Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)","Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_exe

10:22:48
END RequestId: a1ff8f86-ac3e-11e8-a87c-b92e03164e92 `

**Comment by matze1508** [comment]
Hey,
where can i change or add the authentification in the SDK to var s3 = new AWS.S3({signatureVersion: 'v4'});

**Comment by rayj-pgi** [comment]
This has been open for a while. Please re-open if this is still an issue.
