### ISSUE TITLE
incomplete Gemfile for retro_tagging

### ISSUE THREAD

**Issue by sterago** [GorillaStack/auto-tag#51]
The `Gemfile` for the `retro_tagging` tool seems to be lacking the following lines:

```
gem 'terminal-table'
gem 'pastel'
gem 'docopt'
```

Without adding those, the `retro_tag.rb` script fails with errors of the following type:

```
Traceback (most recent call last):
	2: from retro_tag.rb:8:in `<main>'
	1: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- terminal-table (LoadError)
```

**Comment by rayj-pgi** [comment]
This fix has been applied. Thanks @sterago!
