### ISSUE TITLE
error after creating an IAM role

### ISSUE THREAD

**Issue by varunchandak** [GorillaStack/auto-tag#56]
Getting this error in Lambda function after creating an IAM role to test autotag with latest git pull:

```
Syntax error in module 'autotag_event': SyntaxError
const handler = async (cloudtrailEvent, context) => {
^
SyntaxError: Unexpected token (
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
```

**Comment by rayj-pgi** [comment]
my testing shows that this is working, let us know if you are still having issues.
