### ISSUE TITLE
error in lambda function after creating ec2 volume

### ISSUE THREAD

**Issue by varunchandak** [GorillaStack/auto-tag#57]
Getting this error in Lambda function after creating a ec2 volume to test autotag with latest git pull (similar to [this](https://github.com/GorillaStack/auto-tag/issues/56)):

```
Syntax error in module 'autotag_event': SyntaxError
^
SyntaxError: Unexpected token (
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
```

**Comment by rayj-pgi** [comment]
hey @varunchandak - are you running this with the node8.10 runtime?

**Comment by varunchandak** [comment]
@rayj-pgi yes..
