### ISSUE TITLE
New error shown in lambda function

### ISSUE THREAD

**Issue by cdtiwari-ebi** [GorillaStack/auto-tag#90]
I am receiving another error from lambda function.
```
2021-03-08T11:10:37.151Z	d7bf3986-5afb-42d3-9343-ff82d4fafaa9	ERROR	Invoke Error	
{
    "errorType": "ValidationError",
    "errorMessage": "1 validation error detected: Value 'SourceIP: XX.xx.xxx.xxx, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*",
    "code": "ValidationError",
    "message": "1 validation error detected: Value 'SourceIP: XX.XX.XXX.XX, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*",
    "time": "2021-03-08T11:10:37.142Z",
    "requestId": "8265c261-e6a9-4417-865a-c9316c20830a",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 15.10851413887031,
    "stack": [
        "ValidationError: 1 validation error detected: Value 'SourceIP: xx.xxx.xxx.xxx, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}
```

**Comment by cdtiwari-ebi** [comment]
Any idea about this error?

**Comment by rayjanoka** [comment]
Are you adding custom tags? Can I see more of the logs before the error?

**Comment by cdtiwari-ebi** [comment]
Yes, Let me add more logs

**Comment by cdtiwari-ebi** [comment]
Here are the more Error and logs

```

2021-03-24T21:31:38.329Z	72514ee0-9d55-4f90-940d-fbd9f090550c	INFO	{ ValidationError: 1 validation error detected: Value 'SourceIP: xx.xx.xxx.xxx, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)  message:   '1 validation error detected: Value \'SourceIP: 86.16.135.208, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user\' at \'tags.6.member.value\' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*',  code: 'ValidationError',  time: 2021-03-24T21:31:38.281Z,  requestId: 'ca7cdbf1-4550-4232-8c31-ea8177267d8d',  statusCode: 400,  retryable: false,  retryDelay: 1.7868865275104895 } | 2021-03-24T21:31:38.329Z 72514ee0-9d55-4f90-940d-fbd9f090550c INFO { ValidationError: 1 validation error detected: Value 'SourceIP: xx.xx.xxx.xxx, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]* at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) message: '1 validation error detected: Value \'SourceIP: xx.xx.xxx.xxx, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user\' at \'tags.6.member.value\' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*', code: 'ValidationError', time: 2021-03-24T21:31:38.281Z, requestId: 'ca7cdbf1-4550-4232-8c31-ea8177267d8d', statusCode: 400, retryable: false, retryDelay: 1.7868865275104895 }
-- | --
  | 2021-03-24T21:31:38.330+00:00Copy2021-03-24T21:31:38.330Z	72514ee0-9d55-4f90-940d-fbd9f090550c	INFO	ValidationError: 1 validation error detected: Value 'SourceIP: xx.xx.xxx.xxx, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) | 2021-03-24T21:31:38.330Z 72514ee0-9d55-4f90-940d-fbd9f090550c INFO ValidationError: 1 validation error detected: Value 'SourceIP: xx.xx.xxx.xxx, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]* at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  | 2021-03-24T21:31:38.330+00:00Copy2021-03-24T21:31:38.330Z	72514ee0-9d55-4f90-940d-fbd9f090550c	ERROR	Invoke Error	{     "errorType": "ValidationError",     "errorMessage": "1 validation error detected: Value 'SourceIP: 86.16.135.208, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*",     "code": "ValidationError",     "message": "1 validation error detected: Value 'SourceIP: xx.xx.xxx.xxx, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*",     "time": "2021-03-24T21:31:38.281Z",     "requestId": "ca7cdbf1-4550-4232-8c31-ea8177267d8d",     "statusCode": 400,     "retryable": false,     "retryDelay": 1.7868865275104895,     "stack": [         "ValidationError: 1 validation error detected: Value 'SourceIP: 86.16.135.208, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*",         "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29)",         "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",         "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",         "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",         "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",         "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",         "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",         "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",         "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)",         "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"     ] } | 2021-03-24T21:31:38.330Z 72514ee0-9d55-4f90-940d-fbd9f090550c ERROR Invoke Error {"errorType":"ValidationError","errorMessage":"1 validation error detected: Value 'SourceIP: 86.16.135.208, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*","code":"ValidationError","message":"1 validation error detected: Value 'SourceIP: 86.16.135.208, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*","time":"2021-03-24T21:31:38.281Z","requestId":"ca7cdbf1-4550-4232-8c31-ea8177267d8d","statusCode":400,"retryable":false,"retryDelay":1.7868865275104895,"stack":["ValidationError: 1 validation error detected: Value 'SourceIP: 86.16.135.208, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user' at 'tags.6.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*"," at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29)"," at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)"," at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)"," at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)"," at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)"," at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)"," at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10"," at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)"," at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"," at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}


```

**Comment by rayjanoka** [comment]
Weird, it is failing on your "AutoTag_ClientInfo" tag, it says this output is not happy `SourceIP: xxx.xxx.xxx.xxx, UserAgent: aws-cli/2.1.17 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off command/iam.create-user`, but I'm not sure why...I don't see any weird characters. You might try to break that one out to two separate tags and see which one it fails on then.
```
{
  "AutoTag_ManagedBy": "Cloud Team",
  "AutoTag_UserIdentityType": "$event.userIdentity.type",
  "AutoTag_UserName": "$event.userIdentity.userName",
  "AutoTag_ClientInfo": "SourceIP: $event.sourceIPAddress, UserAgent: $event.userAgent"
}
```

**Comment by cdtiwari-ebi** [comment]
Then in that case, kindly update your custom tag example on documentation.

I am using exactly same as defined in example from the document
```
{
  "AutoTag_ManagedBy": "Site Reliability Engineering",
  "AutoTag_UserIdentityType": "$event.userIdentity.type",
  "AutoTag_UserName": "$event.userIdentity.userName",
  "AutoTag_ClientInfo": "SourceIP: $event.sourceIPAddress, UserAgent: $event.userAgent",
  "AutoTag_Ec2_ImageId": "$event.responseElements.instancesSet.items.0.imageId"
}
```

**Comment by rayjanoka** [comment]
Thanks, I've updated the doc. 5bacb5
